### ISSUE TITLE
[Feature]: Add image resizing on hover for Domains section

### ISSUE THREAD

**Issue by GopalVerma1303** [CodeDeployingSquad/website#15]

**Comment by Sumandalai** [comment]
I want to contribute to this issue. Could you please assign it to me?

**Comment by GopalVerma1303** [comment]
Sure

**Comment by GopalVerma1303** [comment]
Commit https://github.com/CodeDeployingSquad/website/commit/02f1b9273c7bd84411ce619d264fd366066f33e4 solved this Issue
