### ISSUE TITLE
[Enhancement]: Make website mobile responsive

### ISSUE THREAD

**Issue by GopalVerma1303** [CodeDeployingSquad/website#19]
### Sections to be covered:
- [ ] Home
- [ ] About
- [ ] Domains
- [ ] Contri. guide
- [ ] Code of conduct
- [ ] Contributors
- [ ] Contact Us

**Comment by GopalVerma1303** [comment]
For reference you can checkout: https://tailwindcss.com/docs/responsive-design

**Comment by rohitmondal03** [comment]
can I work on this issue @GopalVerma1303  ?

**Comment by GopalVerma1303** [comment]
Sure @rohitmondal03 
Here you go!
