### ISSUE TITLE
[Enhancement]: Automate Github Shields/Badges  in README.md

### ISSUE THREAD

**Issue by GopalVerma1303** [CodeDeployingSquad/website#22]
What are Github Shileds? Checkout:
- https://shields.io/
- https://www.youtube.com/watch?v=Dl-ekLb4quE

For guidance, you can checkout:
- https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
- https://dev.to/rocktimsaikia/badge-it-a-github-action-to-automate-adding-badges-to-your-readme-4l4p
- https://github.com/wow-actions/add-badges

**Comment by Achal-00** [comment]
Hey, I would like to work on this.
