### ISSUE TITLE
[Feature]: Add content to the website

### ISSUE THREAD

**Issue by GopalVerma1303** [CodeDeployingSquad/website#8]
## Add content for the following sections
- [x] About.jsx
- [x] ContriGuide.jsx
- [x] Domains.jsx
- [x] Projects.jsx
- [x] Contributors.jsx
- [x] FounderNote.jsx
- [x] CodeOfConduct
- [x] Footer.jsx

**Comment by mansi104-ai** [comment]
Please check Code of conduct section, title error there
